
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eosgvjrlfkyxjlhcbsty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvc2d2anJsZmt5eGpsaGNic3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDkxODksImV4cCI6MjA1OTE4NTE4OX0.euLDVtK20mTAJhA--gmBtmFrjMf1DQUCqRP5Y9VatwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
